In [1]:
import pandas as pd
import numpy as np

# 准备训练数据
origin_training_data = pd.read_csv(r'kddcup.data.corrected', header=None)
print(origin_training_data)

         0    1     2   3    4      5   6   7   8   9   ...   32   33   34  \
0         0  tcp  http  SF  215  45076   0   0   0   0  ...    0  0.0  0.0   
1         0  tcp  http  SF  162   4528   0   0   0   0  ...    1  1.0  0.0   
2         0  tcp  http  SF  236   1228   0   0   0   0  ...    2  1.0  0.0   
3         0  tcp  http  SF  233   2032   0   0   0   0  ...    3  1.0  0.0   
4         0  tcp  http  SF  239    486   0   0   0   0  ...    4  1.0  0.0   
...      ..  ...   ...  ..  ...    ...  ..  ..  ..  ..  ...  ...  ...  ...   
4898426   0  tcp  http  SF  212   2288   0   0   0   0  ...  255  1.0  0.0   
4898427   0  tcp  http  SF  219    236   0   0   0   0  ...  255  1.0  0.0   
4898428   0  tcp  http  SF  218   3610   0   0   0   0  ...  255  1.0  0.0   
4898429   0  tcp  http  SF  219   1234   0   0   0   0  ...  255  1.0  0.0   
4898430   0  tcp  http  SF  219   1098   0   0   0   0  ...  255  1.0  0.0   

           35    36   37    38   39   40       41  
0        0.

In [2]:
# 删除符号列   
origin_training_data_1 = origin_training_data.drop(columns=[1, 2, 3, 6, 11, 20, 21])
print(origin_training_data_1)


         0    4      5   7   8   9   10  12  13  14  ...   32   33   34    35  \
0         0  215  45076   0   0   0   0   0   0   0  ...    0  0.0  0.0  0.00   
1         0  162   4528   0   0   0   0   0   0   0  ...    1  1.0  0.0  1.00   
2         0  236   1228   0   0   0   0   0   0   0  ...    2  1.0  0.0  0.50   
3         0  233   2032   0   0   0   0   0   0   0  ...    3  1.0  0.0  0.33   
4         0  239    486   0   0   0   0   0   0   0  ...    4  1.0  0.0  0.25   
...      ..  ...    ...  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...   ...   
4898426   0  212   2288   0   0   0   0   0   0   0  ...  255  1.0  0.0  0.33   
4898427   0  219    236   0   0   0   0   0   0   0  ...  255  1.0  0.0  0.25   
4898428   0  218   3610   0   0   0   0   0   0   0  ...  255  1.0  0.0  0.20   
4898429   0  219   1234   0   0   0   0   0   0   0  ...  255  1.0  0.0  0.17   
4898430   0  219   1098   0   0   0   0   0   0   0  ...  255  1.0  0.0  0.14   

           36   37    38   

In [3]:
# 筛选正常列
origin_training_data_1_normal = origin_training_data_1.loc[origin_training_data_1.loc[:, 41] == 'normal.']
print(origin_training_data_1_normal)

# 转为numpy矩阵
origin_training_data_2_normal = origin_training_data_1_normal.drop(columns=[41])
X_train_normal = np.array(origin_training_data_2_normal)
print(X_train_normal)

         0    4      5   7   8   9   10  12  13  14  ...   32   33   34    35  \
0         0  215  45076   0   0   0   0   0   0   0  ...    0  0.0  0.0  0.00   
1         0  162   4528   0   0   0   0   0   0   0  ...    1  1.0  0.0  1.00   
2         0  236   1228   0   0   0   0   0   0   0  ...    2  1.0  0.0  0.50   
3         0  233   2032   0   0   0   0   0   0   0  ...    3  1.0  0.0  0.33   
4         0  239    486   0   0   0   0   0   0   0  ...    4  1.0  0.0  0.25   
...      ..  ...    ...  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...   ...   
4898426   0  212   2288   0   0   0   0   0   0   0  ...  255  1.0  0.0  0.33   
4898427   0  219    236   0   0   0   0   0   0   0  ...  255  1.0  0.0  0.25   
4898428   0  218   3610   0   0   0   0   0   0   0  ...  255  1.0  0.0  0.20   
4898429   0  219   1234   0   0   0   0   0   0   0  ...  255  1.0  0.0  0.17   
4898430   0  219   1098   0   0   0   0   0   0   0  ...  255  1.0  0.0  0.14   

           36   37    38   

In [4]:
# 筛选异常列
origin_training_data_1_abnormal = origin_training_data_1.loc[origin_training_data_1.loc[:, 41] != 'normal.']
print(origin_training_data_1_abnormal)

# 转为numpy矩阵
origin_training_data_2_abnormal = origin_training_data_1_abnormal.drop(columns=[41])
X_train_abnormal = np.array(origin_training_data_2_abnormal)
print(X_train_abnormal)


          0     4     5   7   8   9   10  12  13  14  ...   32    33    34  \
7448     184  1511  2957   0   0   3   0   2   1   0  ...    3  1.00  0.00   
7449     305  1735  2766   0   0   3   0   2   1   0  ...    4  1.00  0.00   
40481     79   281  1301   0   0   2   0   1   1   0  ...   10  1.00  0.00   
41114     25   269  2333   0   0   0   0   0   1   0  ...    2  0.03  0.06   
75985      0     0     0   0   0   0   0   0   0   0  ...    2  1.00  0.00   
...      ...   ...   ...  ..  ..  ..  ..  ..  ..  ..  ...  ...   ...   ...   
4867867    0    28     0   3   0   0   0   0   0   0  ...   96  0.38  0.01   
4867868    0    28     0   3   0   0   0   0   0   0  ...   97  0.38  0.01   
4867869    0    28     0   3   0   0   0   0   0   0  ...   98  0.38  0.01   
4867870    0    28     0   3   0   0   0   0   0   0  ...   99  0.39  0.01   
4867871    0    28     0   3   0   0   0   0   0   0  ...  100  0.39  0.01   

           35    36   37   38   39   40                41  
744

In [5]:
mu_normal = np.mean(X_train_normal, axis=0) # 均值
print(mu_normal)
sigma_normal = np.std(X_train_normal, axis=0) # 标准差
print(sigma_normal)
Z_train_normal = (X_train_normal - mu_normal)/(sigma_normal + np.spacing(1)) # 归一化
print(Z_train_normal)
print(np.mean(Z_train_normal, axis=0))
print(np.std(Z_train_normal, axis=0))

[2.17824724e+02 1.47784625e+03 3.23465011e+03 0.00000000e+00
 3.59793211e-05 4.95353014e-02 9.86861380e-05 3.83889077e-02
 3.10450142e-04 1.84008528e-04 6.49704301e-02 5.88724492e-03
 3.62877153e-04 5.13065119e-03 0.00000000e+00 8.15902860e+00
 1.09127902e+01 1.48305734e-03 1.72458138e-03 5.59406999e-02
 5.62064123e-02 9.85257453e-01 1.85353435e-02 1.32494354e-01
 1.48498415e+02 2.02014806e+02 8.44879197e-01 5.65001886e-02
 1.34940166e-01 2.43402986e-02 2.03932848e-03 1.05018499e-03
 5.77844345e-02 5.60155677e-02]
[1.35194318e+03 1.10500363e+05 3.42316630e+04 0.00000000e+00
 1.59989336e-02 9.31912374e-01 1.31411949e-02 8.65356832e+00
 1.76168602e-02 1.81077871e-02 8.83651853e+00 2.76930910e-01
 1.91535218e-02 7.94687911e-02 0.00000000e+00 1.77520160e+01
 2.17904003e+01 2.71998680e-02 2.62097284e-02 2.29009428e-01
 2.27765891e-01 9.30005017e-02 1.17531932e-01 2.76299862e-01
 1.03413307e+02 8.69958939e+01 3.05449230e-01 1.80074194e-01
 2.82299613e-01 5.06992795e-02 2.85378077e-02 1.54236

In [6]:
#基于numpy实现PCA
import numpy as np

covMat_Z_train_normal = np.cov(Z_train_normal,rowvar=False) #计算协方差矩阵，rowvar=0表示数据的每一列代表一个feature
print(covMat_Z_train_normal)
(featValue_Z_train_normal, featVec_Z_train_normal) = np.linalg.eig(covMat_Z_train_normal) #计算协方差矩阵的特征值和特征向量
print("协方差矩阵的特征值：")
print(featValue_Z_train_normal)
print("协方差矩阵的特征向量：")
print(featVec_Z_train_normal)

[[ 1.00000103  0.00297475 -0.00391942 ...  0.02455499 -0.03822372
  -0.03191981]
 [ 0.00297475  1.00000103  0.194611   ...  0.0038366  -0.0029414
  -0.00320122]
 [-0.00391942  0.194611    1.00000103 ...  0.05401232 -0.02101797
  -0.01998123]
 ...
 [ 0.02455499  0.0038366   0.05401232 ...  1.00000103 -0.0082675
  -0.00754061]
 [-0.03822372 -0.0029414  -0.02101797 ... -0.0082675   1.00000103
   0.9589461 ]
 [-0.03191981 -0.00320122 -0.01998123 ... -0.00754061  0.9589461
   1.00000103]]
协方差矩阵的特征值：
[4.58414687e+00 3.79933551e+00 2.50090202e+00 2.04515309e+00
 1.83795966e+00 1.56130468e+00 1.80862637e-03 7.80750641e-03
 3.69475407e-02 2.19264574e-01 1.70901525e-01 7.95078376e-02
 9.39399050e-02 1.10173742e-01 1.02609637e-01 3.76066528e-01
 4.65972115e-01 4.91412806e-01 6.08418057e-01 6.54978221e-01
 1.28863875e+00 1.20026851e+00 1.16534540e+00 7.95119993e-01
 8.50767311e-01 1.06438680e+00 9.36839552e-01 9.49295566e-01
 9.68315448e-01 1.02048233e+00 1.01151585e+00 1.00044695e+00
 0.00000000e

In [7]:
index_Z_train_normal=np.argsort(featValue_Z_train_normal) #将特征值按从小到大排序，index保留的是对应原featValue中的下标
print(index_Z_train_normal)

[33 32  6  7  8 11 12 14 13 10  9 15 16 17 18 19 23 24 26 27 28 31 30 29
 25 22 21 20  5  4  3  2  1  0]


In [8]:
featValue_Z_train_normal_sorted = featValue_Z_train_normal[index_Z_train_normal[-1::-1]] # 从大到小排序后的特征值
print("特征值：")
print(featValue_Z_train_normal_sorted)
featVec_Z_train_normal_sorted = featVec_Z_train_normal[:, index_Z_train_normal[-1::-1]] # 从大到小排序后的特征向量
print("特征向量：")
print(featVec_Z_train_normal_sorted)

特征值：
[4.58414687e+00 3.79933551e+00 2.50090202e+00 2.04515309e+00
 1.83795966e+00 1.56130468e+00 1.28863875e+00 1.20026851e+00
 1.16534540e+00 1.06438680e+00 1.02048233e+00 1.01151585e+00
 1.00044695e+00 9.68315448e-01 9.49295566e-01 9.36839552e-01
 8.50767311e-01 7.95119993e-01 6.54978221e-01 6.08418057e-01
 4.91412806e-01 4.65972115e-01 3.76066528e-01 2.19264574e-01
 1.70901525e-01 1.10173742e-01 1.02609637e-01 9.39399050e-02
 7.95078376e-02 3.69475407e-02 7.80750641e-03 1.80862637e-03
 0.00000000e+00 0.00000000e+00]
特征向量：
[[-7.44029363e-02 -2.99369768e-01 -2.24781633e-02 ... -4.22547686e-04
   0.00000000e+00  0.00000000e+00]
 [-3.13744435e-03 -6.41568499e-03 -1.16388380e-02 ...  4.00681503e-05
   0.00000000e+00  0.00000000e+00]
 [-8.16068618e-03  8.97913030e-03 -7.91714763e-02 ... -8.86902213e-04
   0.00000000e+00  0.00000000e+00]
 ...
 [-5.69841671e-03 -2.27154153e-02 -1.37770642e-01 ... -1.33629504e-03
   0.00000000e+00  0.00000000e+00]
 [ 4.41315244e-01 -8.62763235e-02  2.1050413

In [9]:
# 特征值之和等于方差之和
sum_featValue_Z_train_normal = np.sum(featValue_Z_train_normal_sorted) 
print(sum_featValue_Z_train_normal)
print(np.sum(np.std(Z_train_normal, axis=0))) # 方差已归一化

print(np.sum(featValue_Z_train_normal_sorted[:5])/sum_featValue_Z_train_normal)

32.000032895367255
31.999999999999872
0.46148381168461694


In [10]:
# 主要成分
n_featValue_Z_train_normal_sorted = featValue_Z_train_normal_sorted[:5] # 取前5个成分
print("特征值：")
print(n_featValue_Z_train_normal_sorted)
n_featVec_Z_train_normal_sorted = featVec_Z_train_normal_sorted[:, :5]
print("特征向量：")
print(n_featVec_Z_train_normal_sorted)

特征值：
[4.58414687 3.79933551 2.50090202 2.04515309 1.83795966]
特征向量：
[[-0.07440294 -0.29936977 -0.02247816 -0.03661225  0.07062992]
 [-0.00313744 -0.00641568 -0.01163884  0.01464685 -0.0114032 ]
 [-0.00816069  0.00897913 -0.07917148  0.02724884 -0.03075093]
 [ 0.          0.          0.          0.          0.        ]
 [-0.00063612 -0.00431095 -0.08144809 -0.01991468 -0.00104162]
 [-0.01258287 -0.02951164 -0.00634207  0.01453037 -0.03166145]
 [-0.00117622 -0.00835285 -0.05854378  0.00993093  0.00155401]
 [-0.00334377 -0.01754873 -0.52958667 -0.18394324 -0.00773215]
 [-0.00369389 -0.01157927 -0.31380365 -0.05016937  0.00780622]
 [-0.00452836 -0.0223964  -0.43462498 -0.06337516  0.00610779]
 [-0.00385462 -0.01941064 -0.53811706 -0.18529269 -0.0084773 ]
 [-0.00588113 -0.02578886 -0.05546656  0.06510629  0.00674448]
 [-0.00374428 -0.01055157 -0.00208004  0.00412624  0.00164783]
 [-0.01113052 -0.00564165 -0.22073018 -0.04661381 -0.03036213]
 [ 0.          0.          0.          0.         

In [11]:
Z_train_normal_pc = np.dot(Z_train_normal,n_featVec_Z_train_normal_sorted)
print(Z_train_normal_pc)

Z_train_normal_scores = np.power(Z_train_normal_pc, 2)
Z_train_normal_scores = Z_train_normal_scores/n_featValue_Z_train_normal_sorted
Z_train_normal_scores = np.sum(Z_train_normal_scores, axis=1)

print("主要成分得分：")
print(Z_train_normal_scores)

[[-0.70296888 -1.68767672 -0.03397656  0.17119971 -0.94247949]
 [-0.22688065 -1.6254705   0.13425606 -0.00905641 -0.65500077]
 [-0.24901034 -0.96652086  0.08462707  0.05329187 -0.82782807]
 ...
 [ 0.15241979  0.89422384 -0.06587514  0.12602011  0.15367817]
 [ 0.14005672  0.9508246  -0.06247324  0.11431549  0.22127571]
 [ 0.2349532   0.66371627 -0.0781321   0.27652813 -0.83376766]]
主要成分得分：
[1.35555277 0.94732679 0.63651252 ... 0.23788523 0.27682335 0.54604768]


In [12]:
index_Z_train_normal_scores = np.argsort(Z_train_normal_scores)
Z_train_normal_scores_sorted = Z_train_normal_scores[index_Z_train_normal_scores[-1::-1]]
print(Z_train_normal_scores_sorted)

Z_train_normal_scores_choice = np.int(np.size(Z_train_normal_scores_sorted)*0.01)
print(Z_train_normal_scores_choice)
Z_train_normal_scores_threshold = Z_train_normal_scores_sorted[Z_train_normal_scores_choice]
print("主要组成成分阈值：", Z_train_normal_scores_threshold)

[3.83571938e+05 3.58797810e+04 1.87746761e+04 ... 1.05557422e-03
 1.04349485e-03 1.04345232e-03]
9727
主要组成成分阈值： 31.906802676790846


In [13]:
Z_train_abnormal = (X_train_abnormal - mu_normal)/(sigma_normal + np.spacing(1))
Z_train_abnormal_pc = np.dot(Z_train_abnormal,n_featVec_Z_train_normal_sorted)
Z_train_abnormal_scores = np.power(Z_train_abnormal_pc, 2)
Z_train_abnormal_scores = Z_train_abnormal_scores/n_featValue_Z_train_normal_sorted
Z_train_abnormal_scores = np.sum(Z_train_abnormal_scores, axis=1)

print(Z_train_abnormal_scores > Z_train_normal_scores_threshold)

Z_train_abnormal_res = Z_train_abnormal_scores[Z_train_abnormal_scores > Z_train_normal_scores_threshold]
print(np.size(Z_train_abnormal_res))

print("检出率：", np.size(Z_train_abnormal_res)/np.size(Z_train_abnormal_scores))

[ True  True  True ... False False False]
3897292
检出率： 0.9927762281405627


In [14]:
# 次要成分
n1_featValue_Z_train_normal_sorted = featValue_Z_train_normal_sorted[-1:-4:-1] # 取后3个成分
print("特征值：")
print(n1_featValue_Z_train_normal_sorted)
n1_featVec_Z_train_normal_sorted = featVec_Z_train_normal_sorted[:, -1:-4:-1]
print("特征向量：")
print(n1_featVec_Z_train_normal_sorted)

特征值：
[0.         0.         0.00180863]
特征向量：
[[ 0.00000000e+00  0.00000000e+00 -4.22547686e-04]
 [ 0.00000000e+00  0.00000000e+00  4.00681503e-05]
 [ 0.00000000e+00  0.00000000e+00 -8.86902213e-04]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  6.71379007e-03]
 [ 0.00000000e+00  0.00000000e+00 -9.95817912e-04]
 [ 0.00000000e+00  0.00000000e+00 -2.79257021e-03]
 [ 0.00000000e+00  0.00000000e+00  7.02474481e-01]
 [ 0.00000000e+00  0.00000000e+00  1.46475108e-03]
 [ 0.00000000e+00  0.00000000e+00  2.10534863e-02]
 [ 0.00000000e+00  0.00000000e+00 -7.11247999e-01]
 [ 0.00000000e+00  0.00000000e+00 -1.28072155e-03]
 [ 0.00000000e+00  0.00000000e+00 -3.04724979e-04]
 [ 0.00000000e+00  0.00000000e+00  5.06763508e-03]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -7.32093463e-05]
 [ 0.00000000e+00  0.00000000e+00  2.33948466e-05]
 [ 0.00000000e+00  0.00000000e+00 -1.42368770e-04]
 [ 0.00000000e+00  0.00000000e+00 -2

In [15]:
Z_train_normal_pc1 = np.dot(Z_train_normal,n1_featVec_Z_train_normal_sorted)
print(Z_train_normal_pc1)

Z_train_normal_scores1 = np.power(Z_train_normal_pc1, 2)
Z_train_normal_scores1 = Z_train_normal_scores1/(n1_featValue_Z_train_normal_sorted + np.spacing(1))
Z_train_normal_scores1 = np.sum(Z_train_normal_scores1, axis=1)

print("次要成分得分：")
print(Z_train_normal_scores1)

[[0.         0.         0.02741058]
 [0.         0.         0.0027695 ]
 [0.         0.         0.00121335]
 ...
 [0.         0.         0.00090897]
 [0.         0.         0.00089257]
 [0.         0.         0.00130549]]
次要成分得分：
[0.41542019 0.00424086 0.000814   ... 0.00045682 0.00044049 0.00094232]


In [16]:
index_Z_train_normal_scores1 = np.argsort(Z_train_normal_scores1)
Z_train_normal_scores1_sorted = Z_train_normal_scores1[index_Z_train_normal_scores1[-1::-1]]
print(Z_train_normal_scores1_sorted)

Z_train_normal_scores1_choice = np.int(np.size(Z_train_normal_scores1_sorted)*0.01)
print(Z_train_normal_scores1_choice)
Z_train_normal_scores1_threshold = Z_train_normal_scores1_sorted[Z_train_normal_scores1_choice]
print("次要组成成分阈值：", Z_train_normal_scores1_threshold)

[6.79816332e+04 1.99487781e+04 1.52406157e+04 ... 1.60319257e-13
 7.75787833e-14 1.33866159e-14]
9727
次要组成成分阈值： 2.082700158637442


In [17]:
Z_train_abnormal = (X_train_abnormal - mu_normal)/(sigma_normal + np.spacing(1))
Z_train_abnormal_pc1 = np.dot(Z_train_abnormal,n1_featVec_Z_train_normal_sorted)
Z_train_abnormal_scores1 = np.power(Z_train_abnormal_pc1, 2)
Z_train_abnormal_scores1 = Z_train_abnormal_scores1/(n1_featValue_Z_train_normal_sorted + np.spacing(1))
Z_train_abnormal_scores1 = np.sum(Z_train_abnormal_scores1, axis=1)

print(Z_train_abnormal_scores1 > Z_train_normal_scores1_threshold)

Z_train_abnormal_res1 = Z_train_abnormal_scores[np.logical_or((Z_train_abnormal_scores > Z_train_normal_scores_threshold) , (Z_train_abnormal_scores1 > Z_train_normal_scores1_threshold))]
print(np.size(Z_train_abnormal_res1))

print("检出率：", np.size(Z_train_abnormal_res1)/np.size(Z_train_abnormal_scores1))

[ True  True  True ...  True  True  True]
3900592
检出率： 0.9936168532599697


In [18]:
Z_train_normal = (X_train_normal - mu_normal)/(sigma_normal + np.spacing(1))
Z_train_normal_pc = np.dot(Z_train_normal,n_featVec_Z_train_normal_sorted)
Z_train_normal_scores = np.power(Z_train_normal_pc, 2)
Z_train_normal_scores = Z_train_normal_scores/n_featValue_Z_train_normal_sorted
Z_train_normal_scores = np.sum(Z_train_normal_scores, axis=1)
Z_train_normal_res = Z_train_normal_scores[Z_train_normal_scores > Z_train_normal_scores_threshold]
print(np.size(Z_train_normal_res))

Z_train_normal_pc1 = np.dot(Z_train_normal,n1_featVec_Z_train_normal_sorted)
Z_train_normal_scores1 = np.power(Z_train_normal_pc1, 2)
Z_train_normal_scores1 = Z_train_normal_scores1/(n1_featValue_Z_train_normal_sorted + np.spacing(1))
Z_train_normal_scores1 = np.sum(Z_train_normal_scores1, axis=1)
Z_train_normal_res = Z_train_normal_scores[Z_train_normal_scores1 > Z_train_normal_scores1_threshold]
print(np.size(Z_train_normal_res))

Z_train_normal_res1 = Z_train_normal_scores[np.logical_or((Z_train_normal_scores > Z_train_normal_scores_threshold) , (Z_train_normal_scores1 > Z_train_normal_scores1_threshold))]
print("误报率：", np.size(Z_train_normal_res1)/np.size(Z_train_normal_scores1))

9727
9727
误报率： 0.019300335841263346
